#ifndef QTEVENTBUS_GLOBAL_H
#define QTEVENTBUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTEVENTBUS_LIBRARY)
#  define QTEVENTBUS_EXPORT Q_DECL_EXPORT
#else
#  define QTEVENTBUS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTEVENTBUS_GLOBAL_H
